version: "3.7"
services:

  graphql-server:
    container_name:   graphql-server
    image: graphql
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app